abstract: >-
  Dieser Fragebogen enthält sechs Fragen zum Zustand Ihres Softwaresystems. Nach Beantwortung
  der Fragen erhalten Sie eine erste Einschätzung sowie eine Bewertung Ihres Systems. Danke an
  Thomas Ronzon, der uns die Fragen zur Verfügung gestellt hat. Auf gehts...
questions:
  - id: 1
    text: Die aktuellen Sourcen sind...
    type: single
    options:
      - value: 1
        text: vollständig vorhanden und übersetzbar
        targets:
          - name: fitness
            score: 2
      - value: 2
        text: unvollständig / nicht übersetzbar
        targets:
          - name: fitness
            score: 1
      - value: 4
        text: nicht vorhanden
        targets:
          - name: fitness
            score: 0
  - id: 2
    text: Wer hat Zugriff auf den Server?
    type: single
    options:
      - value: 1
        text: der Administrator
        targets:
          - name: fitness
            score: 2
      - value: 2
        text: die Entwickler
        targets:
          - name: fitness
            score: 1
      - value: 4
        text: keiner
        targets:
          - name: fitness
            score: 0
  - id: 3
    text: Die Entwickler der Anwendung sind...
    type: single
    options:
      - value: 1
        text: immer noch Teil des aktuellen Projektteams
        targets:
          - name: fitness
            score: 2
      - value: 2
        text: nicht mehr Teil des Teams, aber weiterhin im Zugriff
        targets:
          - name: fitness
            score: 1
      - value: 4
        text: nicht mehr im Zugriff
        targets:
          - name: fitness
            score: 0
  - id: 4
    text: Die Server laufen auf...
    type: single
    options:
      - value: 1
        text: aktueller Hardware und Betriebssystemen
        targets:
          - name: fitness
            score: 2
      - value: 2
        text: veralteter Hardware oder Betriebssystemen, können aber aktualisiert werden
        targets:
          - name: fitness
            score: 1
      - value: 4
        text: laufen auf veralteter Hardware oder Betriebssystemen und können nicht mehr aktualisiert werden
        targets:
          - name: fitness
            score: 0
  - id: 5
    text: Die eingesetzte Drittsoftware (Datenbanken, Frameworks, Bibliotheken, etc.) laufen...
    type: single
    options:
      - value: 1
        text: in aktuellen Versionen auf dem aktuellem Betriebssystem
        targets:
          - name: fitness
            score: 2
      - value: 2
        text: in zum Teil veralteten Versionen auf dem aktuellem Betriebssystem
        targets:
          - name: fitness
            score: 1
      - value: 4
        text: nicht mehr auf dem aktuellem Betriebssystem
        targets:
          - name: fitness
            score: 0
  - id: 6
    text: Ein Backup ist...
    type: single
    options:
      - value: 1
        text: vorhanden und die Wiederherstellung wurde getestet
        targets:
          - name: fitness
            score: 2
      - value: 2
        text: vorhanden, doch Wiederherstellung wurde nicht getestet
        targets:
          - name: fitness
            score: 1
      - value: 4
        text: ist nicht vorhanden
        targets:
          - name: fitness
            score: 0
ratings:
  - target: fitness
    values:
      - id: 1
        min: 0
        max: 5
        description: Es besteht akuter Handlungsbedarf, da in einem Fehlerfall nicht das Problem behoben werden kann, sondern erst aufwendige Vorarbeiten erledigt werden müssen. Das System ist akut gefährdet.
      - id: 2
        min: 6
        max: 11
        description: Es besteht Handlungsbedarf, um im Fehlerfall vorbereitet zu sein.
      - id: 3
        min: 12
        max: 12
        description: Es ist alles ok. Sie sind mit Ihrer Software super aufgestellt.
